name: 功能请求
description: 提出新功能或改进建议
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: 请描述你想要的功能
    validations:
      required: true
      
  - type: textarea
    id: usecase
    attributes:
      label: 使用场景
      description: 这个功能在什么场景下有用？