name: 日常任务
description: 创建待办任务
title: "[TASK] "
labels: ["task"]
body:
  - type: textarea
    id: task
    attributes:
      label: 任务内容
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      options:
        - 🔴 高
        - 🟡 中
        - 🟢 低